home_page_boxes:
  REGISTER_OF_LD_APIs:
  - {Power lines: "/power_line/"}
  - {Power stations: "/power_station/"}
  - {Power substations: "/power_substation/"}
  DEFINITIONAL:
  - {Vocabularies: "http://ldweb.ga.gov.au/def/voc/ga/"}
  - {Ontologies: "http://pid.geoscience.gov.au/def/ont/ga/"}
  - {Schemas: "http://pid.geoscience.gov.au/def/schema/ga/"}
  OTHER:
  - {Organisation: "/survey/ga/"}
  - {Organisation3: "/survey/ga/"}
